jeaye/color_coded

CMakeLists.txt
The original Makefile had -pthread, which was missing from CMakeLists.
This would cause color_coded to fail to load because of undefined
symbols.
=> Link against pthread

after/syntax/color_coded.vim
I know users can override it, but might as well have good defaults.
Affected implementations: Vim-qt, Macvim (?)
=> Replaced DarkYellow with hex-equivalent, since some implementations don't recognize it.

.travis.yml
The build matrix consists of g++ 4.9 and clang++ 3.5 both using libstdc++ 4.9. Adding osx is currently not possible as travis has run out of mac workers.
=> Create build matrix for g++ and clang++

.gitignore
Required for #35 due to limitation at https://github.com/Shougo/neobundle.vim/issues/78.
=> Ignore CMake output in case built in main directory. Required for NeoBundle.

README.md
When no branch is given, the badge will display the latest build status.
If an unrelated development branch fails, the user might think the master
is broken. Also, the image was not linking to the travis build page.
=> Only display master build status and link image

.travis.yml
In addition to compiling the library file, we can also check if lua can
load it. This may reveal linker errors such as undefined references.
=> Test if lua can load the library

CMakeLists.txt
When there is a copy of Boost 1.57 headers in `/usr/local/include`, compilation of the Boost version in color_coded tree fails.
In the `CMakeLists.txt` file, by including `cmake/lua.cmake` before `cmake/boost.cmake`, it adds `-I/usr/local/include` to the compiler flags before the flags for the local copy of Boost, which causes the (incompatible) headers from the newer version of Boost to be included when compiling the local Boost source, breaking the build.
=> Change order of CMake includes so Boost will come first

autoload/color_coded.vim
The lua reference manual states that "you cannot put a line break before the '(' in a function call."
This would cause the call to CCerror to fail.
=> Fix ambiguous syntax when calling CCerror

README.md
YCM-Generator now supports automatically generating the `.color_coded` file. This patch adds a note to the README regarding this.
=> README: Added link to YCM-Generator

README.md
I tried installing color_coded with lua5.1 and I kept getting errors saying color_coded wasn't installed, but the compiling process seemed to work just fine.  Upon installing lua5.2 (which is what ubuntu 15.04's vim must use now) color_coded sprang to life.  I updated the instructions to hopefully help someone in a similar situation.
=> Update instructions to match vim's lua version on ubuntu.

.travis.yml
Implements #74 
The new container based infrastructure offers faster boot times and caching. The apt cache is only for private repositories but might be enabled by default soon. After some experimentation I found that caching the clang download does not make a difference and is somewhat cumbersome.
libncurses-dev and libz-dev have been removed from the package list. The code compiled just fine without them. Not sure what they are used for. libz-dev is also not whitelisted.
=> Switch to new travis infrastructure

CMakeLists.txt, cmake/generate_sources.cmake, include/env/environment.hpp, lib/generate_sources
generate_sources is a script that creates a header file. Currently it's configured to only build in-source, but the pull request changes this behaviour by allowing the script to be run from anywhere, and also fixes the cmake procedures to compensate for this.
=> generate_sources can now be run out-of-source.

.travis.yml, CMakeLists.txt, cmake/generate_sources.cmake, include/env/environment.hpp, lib/generate_sources
Travis used to build color_coded in its source directory, but now Travis creates a new directory if it doesn't exist, changes the working directory to the new one, and runs cmake.
=> Travis now builds out-of-source instead of in-source.

colors/twilighted.vim
Previously the twilighted scheme lacked some common boilerplate used by most modern Vim color schemes. The boilerplate is mainly to clear all stale highlight group settings. Otherwise, when a user switches from scheme A to B, some settings in A but not set in B will interfere the final appearance, leading to unexpected/messed-up display. Also, instead of `syntax clear`, `syntax reset` (when and only when syntax is on) is preferred in a color scheme (see "syn-clear").
To see the effect of this patch, try the following with and without the patch:
1. Start vim with "default" colorscheme. Open a C++ file or whatever.
2. `:colorscheme twilighted`
3. `:colorscheme blue`
4. `:colorscheme twilighted`
Without this patch, step 2 will lead to an appearance that is slightly from using twilighted from …
=> Make switching to and from the "twilighted" colorscheme work as expected

include/conf/find.hpp
The new function find_file searches for a file in the given directory.
We can then iterate over an array of possible color_coded files in the
current path.
Cherrypicked from #99. This might be nice to have even if #99 never gets merged.
=> Refactor duplicate code in find()

include/conf/find.hpp, test/include/config.hpp
4b93ded reversed the order of preference for the .color_coded files.
Also added a test for this.
I am terribly sorry for this. This bug is also present in the compilation_database branch.
=> Fix find order for .color_coded files

test/include/config.hpp
Relative paths are resolved relative to the .color_coded file. The test
looked for a directory relative to the current working directory.
Looking at commit 62cd5632624e73cb91ecc63e9e591d34f403ae8f, this seems to be the correct behaviour and the test just had the wrong path.
With this, we could remove the ```|| true``` from the .travis.yml. Ignoring the test results in the ci build seems like a bad idea.
=> Fix path in config file test

include/async/queue.hpp
I've been running with color_coded for a bit now, and it's been really awesome! Thanks for sharing this.
One thing I did notice was that every now and then, when I exit vim that the process would hang. I did a pstack and noticed that the two threads were waiting on thread_.join() and task_cv_.wait.
I checked cppreference and it mentioned that even for atomic variables, you need to acquire the mutex to publish to the waiting thread so I made this change. Seems like its been running fine for me now. 
Figured I might as well share it and get some feedback/thoughts.
=> signal to wake up and exit is missed by queue thread, resulting in deadlock

include/clang/token.hpp
Clang introduced a new type, CXType_Auto for variables that are defined
using auto. These were not highlighted by color_coded because it was
missing in the switch statement.
=> Highlight auto like variables

include/clang/token.hpp
Clang 3.6 did not have the CXType_Auto enum value to denote variables of
type auto. With the new build infrastructure user can now use their
system clang instead of the one bundled with color_coded. Using
CXType_Auto however prevented users from using their older system clang
versions.
The preprocessor check checks for a #define in include/clang-c/Index.h
that gets increased after api additions.
Fixes #123
=> Preserve compatibility with clang 3.6

cmake/generate_sources.cmake
Without this change, the generated files appear wherever one happens to be. This is especially bad for scripts whose working directory is not the build or source directory.
=> Generated headers now always appear in the source directory

autoload/color_coded.vim, include/core.hpp, src/main.cpp
If multiple users try to use the plugin on a single machine, only the
first user is capable of using it, since $tmp/color_coded is owned by
him. This fix addresses this by creating a different folder per user.
Signed-off-by: Nehal J Wani <nehaljw.kkd1@gmail.com>
=> Change temporary path from $tmp/color_coded to $tmp/color_coded-$UID

CMakeLists.txt, autoload/color_coded.vim, cmake/generate_sources.cmake, include/conf/defaults.hpp, lib/generate_sources, src/main.cpp
Changes in the build system broke the generation of default search paths. This commit fixes the bug and furthermore removes a hard-coded version string to make it future-proof. Lastly, `-resource-dir` is used for the clang internal headers/libraries instead of `-isystem` [1].
API version was automatically updated.
Also adding two `REQUIRED` in the main `CMakeLists.txt` for completeness, as at that point they have to be present anyway. Not a big deal though.
Now if one uses the downloaded clang+llvm, they should never run into problems like #131. No hacks needed, for good.
[1] more explanation: stuff inside `lib/clang/<version>/` is indeed internal to clang and should be hidden from users (gcc has similar counterparts), containing `stddef.h`, intrinsics, etc (see related …
=> Fix the default flags for search paths

autoload/color_coded.vim, include/conf/defaults.hpp, src/main.cpp
Prelude: header files are a total mess with so much history burden.
Thanks to the _ingenious_ `#include_next` hack widely used inside STL (c.f. [wrapper headers](https://gcc.gnu.org/onlinedocs/cpp/Wrapper-Headers.html)), the order of search paths does matter, unfortunately. The most important rule for C++ projects is: always include C++ STL headers __before__ system/C headers, as C++ STL will often `#include_next` the underlying C APIs, wrap them, undefine the names from the C headers, and finally redefine the names to the wrappers, in order to achieve things like precise overloads.
If we switch around the order, things will break miserably, which could easily happen right now if anyone (or some tool) puts `-isystem /usr/include` in `.color_coded`. Here's a simple test case:
In an empty …
=> Ensure the order of search paths for C++

autoload/color_coded.vim, include/conf/defaults.hpp, include/conf/load.hpp, src/main.cpp, test/include/config.hpp
I noticed a few issues in the current implementation. Here are the notes in the same order of the commit history:
1. Previously, when compilation database was found, only post-constants would be added; pre-constants were ignored (a by-product of the two PRs developed in parallel).
2. Then I noticed that pre-constants were not actually prepended to arg list as intended, but appended before post-constants.
3. Tests added for 1 & 2.
4. Minor optimization (only include mac-specific paths on macOS).
5. Fix for an unexpected internal error happened due to 1. See the commit comment for details.
=> Various fixes regarding pre/post additions to compilation args

cmake/FindLLVM.cmake
llvm-config for llvm 4 seems to cause additional whitespace to appear in
the LLVM_LDFLAGS. As this is an error in CMake we should strip the LLVM
variables we use of their whitespace to avoid problems in the future.
Note that we currently do not support clang/llvm 4 because the public signature of JSONCompilationDatabase::loadFromFile has changed.
=> Strip llvm variables of whitespace

include/conf/load.hpp
LLVM 4 has changed the function signature of loadFromFile to include a
syntax parameter that dictates how the command line of the compilation
database commands should be parsed. Seeing how the autodetection seems
to be flaky as indicated by the commit that introduced the change, we
should set the syntax to "Gnu" instead of "autodetect" to avoid problems
with our supported platforms.
This does of course mean that we can not support JSON compilation
databases on windows using llvm 4 or higher.
=> Add support for llvm 4.0

README.md
CMake uses XXX_ROOT_DIR nowadays, not ROOT_PATH.
Also update to use clang/llvm40 package.
=> Update FreeBSD configuration instructions

include/conf/load.hpp
Fixes #162
Loading a file that has a relative path in the compile arguments will
fail with an internal error because we only try to find and remove the
absolute path of the file from the compilation arguments.
Now we also try to remove the relative filename if both "file" and the
"command" contain paths relative to the "directory".
Note that this will fail in the case that the "file" is an absolute path
and the "argument" is still relative. For this to work we would have to
make the filename itself a relative path using something like
boost::filesystem::relative, which only got introduced in boost 1.6.
=> Fix compilation database with relative paths
